---
driver_plugin: vagrant
platforms:
- name: centos-6.7
  driver_config:
    customize:
        memory: 3072
- name: centos-5.11
  driver_config:
    customize:
        memory: 3072
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[oracle]
  attributes:
    oracle:
      headless: true
